### PR TITLE
Added instructions for deploying locally on Windows machine in the README

### PR DESCRIPTION
**Pull request by jmmiddour**
# Added Instructions for Deploying API locally on a Windows Machine

---

[Link to the PR Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

---

[Related Trello Card](https://trello.com/c/PTlynJuI)

---

### Location:

- `README.md`

---

### Details:

1. Under the "Deployment" section of the main `README.md` file, I added the instructions on how I was able to make deployment of the API work locally on my Windows 10 Home machine without having to use Linux WSL. 

---

### Committed Features:
1. Added instructions for deploying locally on Windows.
2. Added another path option

---

### Any Issues:
- No issues to report.

### CODE REVIEW

**Review by jeremy-jewett — DISMISSED** [review]
This is a very thorough readme, in my opinion, based on what we've got currently - with room for verbiage as we get this testing suite fleshed out.  I don't see any changes needed at this time.

**Review by jeremy-jewett — DISMISSED** [review]
Based on the error we experienced in a local deployment, this change to the readme was necessary from my earlier approval.  With the changes made, this will help future devs.

**Review by jproctor-rebecca — COMMENTED** [review]
Thank you for adding this deployment option and detailing the Python 3.9 incompatibility.  Excellent reminder note to keep the changes on the local machine.

**Review by jeremy-jewett — APPROVED** [review]
I see you opted to clean up the wording a bit before final approval.  Great job!  Approving for the third time.

**Review by thomasj-s — APPROVED** [review]
I don't believe this is the process I used to get things running on my machine, so I cannot speak to the accuracy of it.  It does however look well written and seems to address any issues that might commonly occur during setup.

**Pull request merged**
