### PR TITLE
Training data pipeline - photo segmentation -

### PR DESCRIPTION
**Pull request by TashaSkyUp**
# Description
This phase takes a black and white (or grayscale) image and segments it into lines of written words.

please see my loom video for a quick run down
https://www.loom.com/share/b7cdf215e51c450c9b9a967ae0a6d5b7

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by Fellylove — APPROVED** [review]
Great work getting this automated. It's going to save us a lot of time.

**Review by ashtilawat — COMMENTED** [review]
Let's try to get some inline comments on this PR. Even if we don't find any mistakes, let's try to leave inline comments saying so.

**Comment by abdishifa234** [comment]
Hey Tasha you did great job and improves the manual cleaning time by a lot but what am I asking what about the lines b/n the texts I mean can you remove it and also can measure the quality of cleaning those images when compared to the manual cleaning and transcription? anyways very nice job!!!

**Review by techthumb1 — APPROVED** [review]
Well written, nicely documented, easy to follow along with the code, despite being unfamiliar with some of the libraries used, so definitely great job. My only suggestion is to run through Pep8 for conventional standards.

**Comment by TashaSkyUp** [comment]
@ashtilawat23 Is it the phase_tkinter_class.py file that needs more comments?

@abdishifa234 Thank you very much for your review. The other parts of the data cleaning pipeline help with line removal. I would like to do some sort of comparison between manual and assisted data cleaning, unfortunately time does not permit.

@techthumb1 ugh! I thought I did.. I mean I know i did several times.. Its probably just not the very last thing I did unfortunately.

**Pull request merged**
