### PR TITLE
Created test subfolder and fixed spelling error

### PR DESCRIPTION
**Pull request by ToddDiFronzo**
# Flushed out the test file and found spelling error: fixed writting to writing
# Created test subfolder to hold our test pictures for text and illustrations

---

[Related Trello Card](https://trello.com/c/r2i5SHzp)

---

### Location:

- file1: app/api/models.py
- file2: app/tests/test_bucket

---

### Details:

1.  Changed word 'writting' to 'writing' on line 20 of models.py file
2.  Created a subfolder in our test file directory in order to test our endpoints (submission/text, submission/illustration)

---

### Committed Features:
1. Changed 'writting' to 'writing'
2. Created folder named test_buckets in app/tests folder

---

### Any Issues:
1. None

### CODE REVIEW

**Review by jeremy-jewett — DISMISSED** [review]
Good catch!

**Review by jmmiddour — DISMISSED** [review]
Good catch on that spelling error.

**Review by jeremy-jewett — APPROVED** [review]
Having the test files nested within the test folder is nice.  This eliminates the possibility of the files being untouchable for one reason or another.

**Review by RAV10K1 — APPROVED** [review]
Went through file with Todd and Jeremy. Good catch on the typo and addition of the test subfolder is helpful for testing purposes.

**Review by jeremy-jewett — APPROVED** [review]
Having the test files nested within the test folder is nice. This eliminates the possibility of the files being untouchable for one reason or another. (previous review was prior to title change)

**Pull request merged**
