### PR TITLE
clipped images and transcribed stories 3101 through 3107

### PR DESCRIPTION
**Pull request by benjcrich**
# Description

Created .png files of each line of a story, transcribed that line into a .txt file under the same name as the snipped .png file. 

## Type of change

Adding more data to be further cleaned and processed by the tesseract model

## Change Status

- [x] Complete, tested, ready to review and merge

## Has This Been Tested

- [x] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [n/a] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

https://www.loom.com/share/96fb05f5f7434d18a28b254e18236c5a

### CODE REVIEW

**Review by BritVandy — APPROVED** [review]
Looks good. Nice job!

**Review by cryptobellum — COMMENTED** [review]
Great work completing this foundational task.

**Review by Fellylove — APPROVED** [review]
Thanks for doing this.

It is well organized in terms of labelling. 

I found a few things you might have to look at or get corrected during the preprocessing.

data/storysquad-ground-truth-31/3102/31-3102-1-18.gt.txt (should add space between is and probably)
data/storysquad-ground-truth-31/3102/31-3102-1-20.gt.txt (it is Mrs. Kapleu nor Kableu)

data/storysquad-ground-truth-31/3102/31-3102-2-10.png(it is Isabella not Igabella)
data/storysquad-ground-truth-31/3102/31-3102-2-13.gt.txt(it is Play not Dlay)
data/storysquad-ground-truth-31/3106/31-3106-1-10.gt.txt(it is Lets not Lsts)

**Comment by abdishifa234** [comment]
It looks every thing good, nice job!!

**Review by Zerkue — COMMENTED** [review]
Great job benj! Here are a few things I noticed:

data/storysquad-ground-truth-31/3101/31-3101-1-23.png   v v v v v v v v v v 
data/storysquad-ground-truth-31/3101/31-3101-1-25.png:  I feel like we can cut the top a little more just to reduce the number of pencil marks from other lines on the paper.

**Pull request merged**
