### PR TITLE
Evaluating/ Added evaluation metrics using some extra libraries, change output paths using .env variables, evaluated pytesseract with images at different preprocessing stages. Added a google vision for comparison of the metrics methods 

### PR DESCRIPTION
**Pull request by urenajose**
Passed images at different stages of preprocessing to pytesseract to its performance to evaluate performance.

### CODE REVIEW

**Review by DevvinK — APPROVED** [review]
Looks good.

**Review by DevvinK — DISMISSED** [review]
Looks good.

**Review by ranaharoonkhan — DISMISSED** [review]
Looks great

**Review by paulteeter — APPROVED** [review]
These look great, Jose! I love the metrics you've provided in the comparisons of different iterations of processing methods. 

Lots of great work here!

**Review by ranaharoonkhan — APPROVED** [review]
Looks good to me .

**Pull request merged**
