### PR TITLE
Fixed bug so the StoryText API endpoint is usable

### PR DESCRIPTION
**Pull request by afroman32**
# Description
I updated the complexities function in the wordcloud_functions.py to return the words and their complexities. I also updated the endpoint in the wordcloud_database.py function to use the new complexities_df function instead of the clean_text which was deleted by someone.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by ppmorgoun — DISMISSED** [review]
Looks good - not sure why so many lines were commented out in the first place. Thanks for your work

**Review by masonmenges — APPROVED** [review]
Well having so much code commented out definitely wouldn't have been helpful, it all looks good to me 👍🏼

**Comment by WhyseRabbit** [comment]
It looks a lot cleaner, now. Thank you for your hard work!

**Comment by Cgcollins91** [comment]
Great work resolving this issue

**Review by bofori20 — APPROVED** [review]
A whole lot cleaner. Thanks Mucho!

**Pull request merged**
