### PR TITLE
Basic pipeline for automating image processing steps

### PR DESCRIPTION
**Pull request by WhyseRabbit**
Co-authored by Petr Morgoun - ppmorgoun@gmail.com
Co-authored by Carl Stimson - carlstimson@gmail.com
Co-authored by Alex Yeary - mercy719@gmail.com

Loom video: https://www.loom.com/share/5b2395fa2b1d4f7a85a4648d65915f16

# Description

Creates a basic framework for automating the pre-processing of story images. The ultimate goal is to create an automated process for creating training data for the OCR model that can also be used to preprocess new story submissions to send to the OCR model.

The following aspects can be found in `data_management/autopreprocess_testing`.

`preprocessing_functions.py` contains all of the small processing steps, such as noise removal, gray scaling, etc.
`processing_pipeline.py` puts the functions together in a pipeline that accepts a single image page and returns a processed image.
`preprocess_directory.py` takes all images in a directory (including nested directory), puts them through the above pipeline, then saves them in a different directory. 

The functionality is very basic but functional. This provides a framework for easy experimentation with processing techniques, the order of steps, hyperparameters, etc.  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by WhyseRabbit** [comment]
The work contained was contributed to by @ppmorgoun and @stimsonc

**Review by stimsonc — APPROVED** [review]
Thanks @WhyseRabbit and @ppmorgoun! I'm pumped we got a functional basic pipeline submitted before the end of the sprint.

**Comment by Cgcollins91** [comment]
Great progress toward deterministic preprocessing

**Review by masonmenges — APPROVED** [review]
This looks awesome, I'm excited to see how this changes going forward and what gets added to this pipeline

**Pull request merged**
