### PR TITLE
Added imports, `TestCase` class for testing the histogram and dummy data

### PR DESCRIPTION
**Pull request by jmmiddour**
# Created the test file for the visualization endpoints

---

[Link to the PR Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

---

[Related Trello Card - viz/linegraph](https://trello.com/c/8PKBmNuh)
[Related Trello Card - viz/histograph](https://trello.com/c/l4arGU8p)

---

### Location:

- app/tests/test_visualization.py

---

### Details:

I created the file for testing the endpoints in the `visualization.py` file. This is still a work in progress, however, it will not break anything if merged with main once my other pull request is approved by Jeannine. 

So far this is what I have done with this file:

1. Added the imports I know we were going to need for both of the tests.
2. Added the `TestCase` class for the `viz/histogram` endpoint for Thomas.
3. Added the `setUpClass` class method to instantiate the dummy data when the `TestCase` starts.
4. Added the `setUp` method to break down the dummy data into usable variables for tests.
5. Defined and added docstrings for the tests that Thomas could write for this endpoint.

---

### Committed Features:
1. Added all of the items listed above in the "details" section to the empty file.

---

### Any Issues:

None.

### CODE REVIEW

**Review by RAV10K1 — APPROVED** [review]
Nice job as usual Joanne!

**Review by ToddDiFronzo — APPROVED** [review]
Looks like a good start.

**Review by jproctor-rebecca — CHANGES_REQUESTED** [review]
please resolve merge conflicts

**Comment by jmmiddour** [comment]
I believe that I have resolved the merge conflict now. Please let me know if it is still not showing as resolved on your end.

**Review by jproctor-rebecca — APPROVED** [review]

**Pull request merged**
