### PR TITLE
Transcribed and cropped version 

### PR DESCRIPTION
**Pull request by abdishifa234**
**Description**
Created .png files of each line of a story, transcribed that line into a .txt file under the same name as the snipped .png file.
**Type of change**
Adding more data to be further cleaning and preprocessing then fed to the tesseract model
Change Status
☑︎ Complete, tested, ready to review and merge

Has This Been Tested
☑︎ Not necessary
Checklist
☑︎ My code follows the style guidelines of this project
☑︎ I have performed a self-review of my own code
• [n/a] I have commented my code, particularly in hard-to-understand areas
• [n/a] I have made corresponding changes to the documentation
• [n/a] My changes generate no new warnings

### CODE REVIEW

**Review by Fellylove — APPROVED** [review]
Great work! Thanks for doing this
It is well organized. 

There are just a few things to note. 
data/storysquad-ground-truth-31/3116/31-3116-16-1.gt.txt.txt (it is river NOT riever)
data/storysquad-ground-truth-31/3116/31-3116-17-1.gt.txt.txt (it is zip NOT zio)
data/storysquad-ground-truth-31/3116/31-3116-34-2.gt.txt.txt ( it is turtle NOT turle)
data/storysquad-ground-truth-31/3119/31-3119-8-1.gt.txt.txt (it is dinoursar NOT dinoursor)
data/storysquad-ground-truth-31/3120/31-3120-13-1.gt.txt.txt (It is medatating NOT medating)
data/storysquad-ground-truth-31/3120/31-3120-9-1.gt.txt.txt (it is was NOT eas)

Otherwise, everything looks great.

**Review by cryptobellum — DISMISSED** [review]
In addition to the specifics that @Fellylove mentioned, it looks like in file 31-3115-12-1 the transcribed "No" should be "NO" (capital letter O based on how the writer appears to have written lowercase o's). Otherwise, your works looks great!

**Review by Zerkue — COMMENTED** [review]
This will work amazing for the model! These are a few minor things I saw that I would do a little differently.

For data/storysquad-ground-truth-31/3119/31-3119-5-1.png.PNG: v v v v v v v v v v v
data/storysquad-ground-truth-31/3120/31-3120-18-1.png.PNG:   It is possible to get a cleaner cut if we rotate the paper a few degrees in the correct direction to get the best results

For data/storysquad-ground-truth-31/3119/31-3119-11-1.png.PNG I think we can cut all the empty space on the right that has no text at all and just leave the words needed

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Please add a loom video explaining your code.

**Pull request closed without merging**
