### PR TITLE
feature/management_utils_update

### PR DESCRIPTION
**Pull request by TashaSkyUp**
Quick update to a test, which tests that images and stories for the data training pipeline are readable.

Replace with description of PR

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by DoctorDroid — DISMISSED** [review]
Nice work. Clean and Pep8 compliant. Extreme attention to detail. 

Tasha left no character out of place and even found a single letter missing in an acronym in a comment (line 62) and a typo in the comment about typos (line 82) 

Attention was also paid to ensure the code is DRY. Lastly, a test was included to ensure the image size is large enough to work with effectively with our pipeline.

**Review by peterger8y — DISMISSED** [review]

**Review by ashtilawat — COMMENTED** [review]
Looks like some of the check aren't passing? Do we know what's happening there?

**Comment by TashaSkyUp** [comment]
@ashtilawat23 Looks like it's being particular about a couple things.. I'll take a look. Try to decode what the issues are. To bad there isn't an easy way to iterate on changes to see what it likes and doesn't.

**Review by peterger8y — DISMISSED** [review]

**Comment by TashaSkyUp** [comment]
@peterger8y @ashtilawat23 @DoctorDroid I give up on making the linter happy, hopefully it will let us continue even if it is not.

**Comment by peterger8y** [comment]
"isort. isort helps to sort and format imports in your Python code. Black also formats imports, but in a different way from isort's defaults which leads to conflicting changes." - from google

It looks like we need to make a decision between ISORT and BLACK

**Comment by peterger8y** [comment]
There could be other contradictions between those linters, I'm not sure. Just found the one

**Comment by TashaSkyUp** [comment]
Things like this should be integrated into our ides.

**Comment by TashaSkyUp** [comment]
@peterger8y @DoctorDroid  yeah its happy now. yessh! please re-review, when you have the time.

Ohhh this is why I (Tim) couldn't find the mesage/thread on Slack.

**Comment by peterger8y** [comment]
Good job getting it past the linter!

**Review by peterger8y — APPROVED** [review]
Well written tests, good job getting it past the linter

**Review by DoctorDroid — APPROVED** [review]
repair of the testing code to reflect the latest PR in image resolution verification. and cleanup of code structure. Well played @TashaSkyUp , well played.

**Pull request merged**
