### PR TITLE
Added a table of contents to the top of README

### PR DESCRIPTION
**Pull request by TemsyChen**
# Description

Added a table of contents to the top of the README.md. Because the README is quite long and dense, this will help future cohorts skim the doc and get an idea of its contents quickly, and hopefully streamline the onboarding process. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [X] Not necessary

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by SaraWestWA — APPROVED** [review]
The table of contents will be very useful. Good work.

**Review by RAV10K1 — APPROVED** [review]
Good job making the readme more readable. Approved with thanks!

**Review by jrslagle — APPROVED** [review]
Looks nice and readable. Thanks for doing this!

**Comment by mark-blasquino** [comment]
Great job on adding this helpful item @TemsyChen!

**Pull request merged**
