### PR TITLE
README.md dynamic table of contents

### PR DESCRIPTION
**Pull request by SaraWestWA**
# Description

Dynamic table of contents as suggested by Temsy who created a static option
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [x] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by ahvblackwelltech — DISMISSED** [review]
Dynamic table of contents looks great

**Review by TemsyChen — CHANGES_REQUESTED** [review]
Nice job! I didn't think it would be this simple to do, and it's great. My suggestion is to remove or fix the links that don't work.

**Comment by SaraWestWA** [comment]
All links should be functional, including the black subheadings.

**Review by TemsyChen — CHANGES_REQUESTED** [review]
I tested it, and it's working better, but the following links have issues: What is Story Squad, Scope, Features, Gamification/Clustering, Meet the Team.

**Comment by SaraWestWA** [comment]
All links are now functional in both VS Code and GitHub

**Review by TemsyChen — APPROVED** [review]
Works beautifully!

**Comment by jrslagle** [comment]
Tested all the links myself and they all work beautifully. I don't see any missing links either.

**Review by jrslagle — APPROVED** [review]

**Pull request merged**
